// Code generated by the klever-sc build system. DO NOT EDIT.
////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                            5
// Total number of exported functions:   7

#![no_std]

klever_sc_wasm_adapter::allocator!();
klever_sc_wasm_adapter::panic_handler!();

klever_sc_wasm_adapter::endpoints! {
    deehr_identity_registry
    (
        init => init
        upgrade => upgrade
        keyHistory => key_history
        registerDid => register_did
        resolveDid => resolve_did
        updateDid => update_did
        deactivateDid => deactivate_did
    )
}
